# Change these first
owner: luxtagofficial # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
# Offical Websites
  - name: LuxTag.io
    url: https://www.luxtag.io
  - name: BrandTag.io
    url: https://www.brandtag.io
#   - name: eScroll.my
#     url: https://e-scroll.my
# BrandTag Production
  - name: BrandTag
    url: https://app.brandtag.io
  - name: BrandTag API
    url: https://api.brandtag.io
  - name: BrandTag Blockchain Explorer
    url: https://blox.brandtag.io
  - name: BrandTag Blockchain API
    url: https://rest.brandtag.io/chain/height
# Papyrus
  - name: Papyrus
    url: https://papyrus.luxtag.io
  - name: Papyrus API
    url: https://x2.event.luxtag.io
# eScroll
  - name: eScroll Demo
    url: https://escroll.demo.luxtag.io
  - name: eScroll Demo API
    url: https://escrollapi.demo.luxtag.io
# BrandTag Staging
  - name: BrandTag Staging
    url: https://app.staging.brandtag.io
  - name: BrandTag Staging API
    url: https://api.staging.brandtag.io
  - name: BrandTag Staging Blockchain Explorer
    url: https://blox.staging.brandtag.io
  - name: BrandTag Staging Blockchain API
    url: https://rest.staging.brandtag.io/node/info
# Scribe Staging
  - name: Scribe Staging
    url: https://app.staging.scribeme.io
  - name: Scribe Staging API
    url: https://api.staging.scribeme.io
  - name: Scribe Staging Blockchain Explorer
    url: https://blox.staging.scribeme.io
  - name: Scribe Staging Blockchain API
    url: https://rest.staging.scribeme.io/node/info

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a LuxTag status page which uses **real-time** data from our [GitHub repository](https://github.com/$OWNER/$REPO).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
